//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LahmaOnline.MultiLanguage {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MLResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MLResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LahmaOnline.MultiLanguage.MLResource", typeof(MLResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AED.0.00 - AED.15.00.
        /// </summary>
        internal static string _00TO15 {
            get {
                return ResourceManager.GetString("00TO15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AED.15.00 - AED.30.00.
        /// </summary>
        internal static string _15TO30 {
            get {
                return ResourceManager.GetString("15TO30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AED.30.00 - AED.45.00.
        /// </summary>
        internal static string _30TO45 {
            get {
                return ResourceManager.GetString("30TO45", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AED.45.00 - AED.60.00.
        /// </summary>
        internal static string _45TO60 {
            get {
                return ResourceManager.GetString("45TO60", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Us.
        /// </summary>
        internal static string AboutUs {
            get {
                return ResourceManager.GetString("AboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept Edit Information.
        /// </summary>
        internal static string AcceptEditInformation {
            get {
                return ResourceManager.GetString("AcceptEditInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address must not be Empty.
        /// </summary>
        internal static string AddressEmptyMessage {
            get {
                return ResourceManager.GetString("AddressEmptyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Review.
        /// </summary>
        internal static string AddReview {
            get {
                return ResourceManager.GetString("AddReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add To Cart.
        /// </summary>
        internal static string AddToCart {
            get {
                return ResourceManager.GetString("AddToCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AED.
        /// </summary>
        internal static string AED {
            get {
                return ResourceManager.GetString("AED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Categories.
        /// </summary>
        internal static string AllCategories {
            get {
                return ResourceManager.GetString("AllCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow.
        /// </summary>
        internal static string Allow {
            get {
                return ResourceManager.GetString("Allow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string AllPrice {
            get {
                return ResourceManager.GetString("AllPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        internal static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic Full Name must not be Empty.
        /// </summary>
        internal static string ArabicNameEmptyMessage {
            get {
                return ResourceManager.GetString("ArabicNameEmptyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birthday.
        /// </summary>
        internal static string Birthday {
            get {
                return ResourceManager.GetString("Birthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birthday must old 4 years from Now.
        /// </summary>
        internal static string BirthdayRuleMessage {
            get {
                return ResourceManager.GetString("BirthdayRuleMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy Now.
        /// </summary>
        internal static string BuyNow {
            get {
                return ResourceManager.GetString("BuyNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cart Summary.
        /// </summary>
        internal static string CartSummary {
            get {
                return ResourceManager.GetString("CartSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        internal static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        internal static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Out.
        /// </summary>
        internal static string CheckOut {
            get {
                return ResourceManager.GetString("CheckOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click On Map To Select Location.
        /// </summary>
        internal static string ClickOnMapToSelectLocation {
            get {
                return ResourceManager.GetString("ClickOnMapToSelectLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        internal static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        internal static string ContactUs {
            get {
                return ResourceManager.GetString("ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue Without Signin.
        /// </summary>
        internal static string ContinueWithoutSignin {
            get {
                return ResourceManager.GetString("ContinueWithoutSignin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Password.
        /// </summary>
        internal static string CurrentPassword {
            get {
                return ResourceManager.GetString("CurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string DeliveryAddress {
            get {
                return ResourceManager.GetString("DeliveryAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery Areas.
        /// </summary>
        internal static string DeliveryAreas {
            get {
                return ResourceManager.GetString("DeliveryAreas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery Charges.
        /// </summary>
        internal static string DeliveryCharges {
            get {
                return ResourceManager.GetString("DeliveryCharges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery Infromation.
        /// </summary>
        internal static string DeliveryInfromation {
            get {
                return ResourceManager.GetString("DeliveryInfromation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Denied.
        /// </summary>
        internal static string Denied {
            get {
                return ResourceManager.GetString("Denied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details Invoice.
        /// </summary>
        internal static string DetailsInvoice {
            get {
                return ResourceManager.GetString("DetailsInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DONE.
        /// </summary>
        internal static string DONE {
            get {
                return ResourceManager.GetString("DONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        internal static string E_mail {
            get {
                return ResourceManager.GetString("E_mail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Your Information.
        /// </summary>
        internal static string EditYourInformation {
            get {
                return ResourceManager.GetString("EditYourInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email must like this &quot;user@host.com&quot;.
        /// </summary>
        internal static string EmailFormatMessage {
            get {
                return ResourceManager.GetString("EmailFormatMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English Full Name must not be Empty.
        /// </summary>
        internal static string EnglishNameEmptyMessage {
            get {
                return ResourceManager.GetString("EnglishNameEmptyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your email and we&apos;ll send you a link to get back into your account..
        /// </summary>
        internal static string Enter_your_username_or_email {
            get {
                return ResourceManager.GetString("Enter_your_username_or_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, fill in all fields to continue\n Or some Value not Valid.
        /// </summary>
        internal static string ErrorMissingValue {
            get {
                return ResourceManager.GetString("ErrorMissingValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluation.
        /// </summary>
        internal static string Evaluation {
            get {
                return ResourceManager.GetString("Evaluation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;re sorry, but something went wrong. Please try again.
        /// </summary>
        internal static string FailedMessage {
            get {
                return ResourceManager.GetString("FailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed Opration.
        /// </summary>
        internal static string FailedOpration {
            get {
                return ResourceManager.GetString("FailedOpration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fat.
        /// </summary>
        internal static string Fat {
            get {
                return ResourceManager.GetString("Fat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WishList.
        /// </summary>
        internal static string Favourites {
            get {
                return ResourceManager.GetString("Favourites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        internal static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        internal static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter by price.
        /// </summary>
        internal static string Filterbyprice {
            get {
                return ResourceManager.GetString("Filterbyprice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forget Password.
        /// </summary>
        internal static string ForgetPassword {
            get {
                return ResourceManager.GetString("ForgetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for a link to reset your password..
        /// </summary>
        internal static string ForLinkToResetYourPassword {
            get {
                return ResourceManager.GetString("ForLinkToResetYourPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        internal static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name Arabic.
        /// </summary>
        internal static string FullNameAr {
            get {
                return ResourceManager.GetString("FullNameAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name English.
        /// </summary>
        internal static string FullNameEn {
            get {
                return ResourceManager.GetString("FullNameEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        internal static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GOOD.
        /// </summary>
        internal static string GOOD {
            get {
                return ResourceManager.GetString("GOOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have internet connection.
        /// </summary>
        internal static string InternetConnectionMessage {
            get {
                return ResourceManager.GetString("InternetConnectionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internet Connection.
        /// </summary>
        internal static string InternetConnectionTitle {
            get {
                return ResourceManager.GetString("InternetConnectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Date.
        /// </summary>
        internal static string InvoiceDate {
            get {
                return ResourceManager.GetString("InvoiceDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Id.
        /// </summary>
        internal static string InvoiceID {
            get {
                return ResourceManager.GetString("InvoiceID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to items.
        /// </summary>
        internal static string items {
            get {
                return ResourceManager.GetString("items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kg.
        /// </summary>
        internal static string Kg {
            get {
                return ResourceManager.GetString("Kg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Large.
        /// </summary>
        internal static string Large {
            get {
                return ResourceManager.GetString("Large", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Invoice.
        /// </summary>
        internal static string LastInvoice {
            get {
                return ResourceManager.GetString("LastInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Later.
        /// </summary>
        internal static string Later {
            get {
                return ResourceManager.GetString("Later", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let&apos;s get started.
        /// </summary>
        internal static string Let_sgetstarted {
            get {
                return ResourceManager.GetString("Let\'sgetstarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License.
        /// </summary>
        internal static string License {
            get {
                return ResourceManager.GetString("License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load More.
        /// </summary>
        internal static string LoadMore {
            get {
                return ResourceManager.GetString("LoadMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        internal static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        internal static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium.
        /// </summary>
        internal static string Medium {
            get {
                return ResourceManager.GetString("Medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing Value.
        /// </summary>
        internal static string MissingValue {
            get {
                return ResourceManager.GetString("MissingValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More.
        /// </summary>
        internal static string More {
            get {
                return ResourceManager.GetString("More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More Details.
        /// </summary>
        internal static string MoreDetails {
            get {
                return ResourceManager.GetString("MoreDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can not add this product to your favorites list without subscribing with us. Do you want to subscribe with us?.
        /// </summary>
        internal static string MustLogin {
            get {
                return ResourceManager.GetString("MustLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must Select Your Emarities.
        /// </summary>
        internal static string MustSelectEmaritiesMessage {
            get {
                return ResourceManager.GetString("MustSelectEmaritiesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must Select Your Gender.
        /// </summary>
        internal static string MustSelectGenderMessage {
            get {
                return ResourceManager.GetString("MustSelectGenderMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must Select Your Nationality.
        /// </summary>
        internal static string MustSelectNationalityMessage {
            get {
                return ResourceManager.GetString("MustSelectNationalityMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Cart.
        /// </summary>
        internal static string MyCart {
            get {
                return ResourceManager.GetString("MyCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Orders.
        /// </summary>
        internal static string MyOrders {
            get {
                return ResourceManager.GetString("MyOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Address.
        /// </summary>
        internal static string NewAddress {
            get {
                return ResourceManager.GetString("NewAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Arrival.
        /// </summary>
        internal static string NewArrival {
            get {
                return ResourceManager.GetString("NewArrival", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        internal static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No invoices have been generated yet.
        /// </summary>
        internal static string NoInvoice {
            get {
                return ResourceManager.GetString("NoInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Shopping Cart is empty.
        /// </summary>
        internal static string NoItemInCart {
            get {
                return ResourceManager.GetString("NoItemInCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No more invoice.
        /// </summary>
        internal static string NoMoreInvoice {
            get {
                return ResourceManager.GetString("NoMoreInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No more item.
        /// </summary>
        internal static string NoMoreItem {
            get {
                return ResourceManager.GetString("NoMoreItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        internal static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number Phone.
        /// </summary>
        internal static string NumberPhone {
            get {
                return ResourceManager.GetString("NumberPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number phone must be 10 digit only.
        /// </summary>
        internal static string NumberPhoneMessage {
            get {
                return ResourceManager.GetString("NumberPhoneMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Origin.
        /// </summary>
        internal static string Origin {
            get {
                return ResourceManager.GetString("Origin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        internal static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contint Lower letter, Upper letter, Digit number and Symbol. Also Must be more then 6 character.
        /// </summary>
        internal static string PasswordRuleMessage {
            get {
                return ResourceManager.GetString("PasswordRuleMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Online.
        /// </summary>
        internal static string PaymentByCreditCard {
            get {
                return ResourceManager.GetString("PaymentByCreditCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment less than 50 AED.
        /// </summary>
        internal static string PaymentLessThan50AED {
            get {
                return ResourceManager.GetString("PaymentLessThan50AED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Cash.
        /// </summary>
        internal static string PaymentUponReceipt {
            get {
                return ResourceManager.GetString("PaymentUponReceipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission.
        /// </summary>
        internal static string Permission {
            get {
                return ResourceManager.GetString("Permission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to if you want select your location, we will need access to your location.
        /// </summary>
        internal static string PermissionGetLocation {
            get {
                return ResourceManager.GetString("PermissionGetLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We need storage permission to save your information.
        /// </summary>
        internal static string PermissionMessage {
            get {
                return ResourceManager.GetString("PermissionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        internal static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please agree terms and conditions.
        /// </summary>
        internal static string PleaseAgreeTermsAndConditions {
            get {
                return ResourceManager.GetString("PleaseAgreeTermsAndConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        internal static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product tags.
        /// </summary>
        internal static string Producttags {
            get {
                return ResourceManager.GetString("Producttags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        internal static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promotion Discounts.
        /// </summary>
        internal static string PromotionDiscounts {
            get {
                return ResourceManager.GetString("PromotionDiscounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipient Details.
        /// </summary>
        internal static string RecipientDetails {
            get {
                return ResourceManager.GetString("RecipientDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RESET.
        /// </summary>
        internal static string RESET {
            get {
                return ResourceManager.GetString("RESET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart &quot;LahmaOnline&quot; to see the change.
        /// </summary>
        internal static string RestartToSeeChange {
            get {
                return ResourceManager.GetString("RestartToSeeChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roughly.
        /// </summary>
        internal static string Roughly {
            get {
                return ResourceManager.GetString("Roughly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type Item Name.
        /// </summary>
        internal static string SearchYourProduet {
            get {
                return ResourceManager.GetString("SearchYourProduet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Date Birthday.
        /// </summary>
        internal static string SelectDateBirthday {
            get {
                return ResourceManager.GetString("SelectDateBirthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Emarities.
        /// </summary>
        internal static string SelectEmarities {
            get {
                return ResourceManager.GetString("SelectEmarities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Gender.
        /// </summary>
        internal static string SelectGender {
            get {
                return ResourceManager.GetString("SelectGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Language.
        /// </summary>
        internal static string SelectLanguage {
            get {
                return ResourceManager.GetString("SelectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Nationality.
        /// </summary>
        internal static string SelectNationality {
            get {
                return ResourceManager.GetString("SelectNationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Origin.
        /// </summary>
        internal static string SelectOrigin {
            get {
                return ResourceManager.GetString("SelectOrigin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Recieve Location.
        /// </summary>
        internal static string SelectRecieveLocation {
            get {
                return ResourceManager.GetString("SelectRecieveLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Login Link.
        /// </summary>
        internal static string Send_Login_Link {
            get {
                return ResourceManager.GetString("Send_Login_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping Address.
        /// </summary>
        internal static string ShippingAddress {
            get {
                return ResourceManager.GetString("ShippingAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        internal static string Signin {
            get {
                return ResourceManager.GetString("Signin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signout.
        /// </summary>
        internal static string Signout {
            get {
                return ResourceManager.GetString("Signout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up.
        /// </summary>
        internal static string Signup {
            get {
                return ResourceManager.GetString("Signup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip Without Sign in.
        /// </summary>
        internal static string SkipWithoutSignin {
            get {
                return ResourceManager.GetString("SkipWithoutSignin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Small.
        /// </summary>
        internal static string Small {
            get {
                return ResourceManager.GetString("Small", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soft.
        /// </summary>
        internal static string Soft {
            get {
                return ResourceManager.GetString("Soft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specification Item.
        /// </summary>
        internal static string SpecificationItem {
            get {
                return ResourceManager.GetString("SpecificationItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store.
        /// </summary>
        internal static string Store {
            get {
                return ResourceManager.GetString("Store", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STRONG.
        /// </summary>
        internal static string STRONG {
            get {
                return ResourceManager.GetString("STRONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit your comment.
        /// </summary>
        internal static string SubmitYourComment {
            get {
                return ResourceManager.GetString("SubmitYourComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscribe With Us.
        /// </summary>
        internal static string SubscribeWithUs {
            get {
                return ResourceManager.GetString("SubscribeWithUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtotal.
        /// </summary>
        internal static string Subtotal {
            get {
                return ResourceManager.GetString("Subtotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax.
        /// </summary>
        internal static string Tax {
            get {
                return ResourceManager.GetString("Tax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms &amp; Conditions.
        /// </summary>
        internal static string Terms_conditions {
            get {
                return ResourceManager.GetString("Terms&conditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks! Please check.
        /// </summary>
        internal static string Thanks_PleaseCheck {
            get {
                return ResourceManager.GetString("Thanks!PleaseCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no item yet.
        /// </summary>
        internal static string ThereIsNoItemYet {
            get {
                return ResourceManager.GetString("ThereIsNoItemYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Work.
        /// </summary>
        internal static string TimeWork {
            get {
                return ResourceManager.GetString("TimeWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following information should be corrected:.
        /// </summary>
        internal static string TitleMessage {
            get {
                return ResourceManager.GetString("TitleMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lahma Online.
        /// </summary>
        internal static string TitleProject {
            get {
                return ResourceManager.GetString("TitleProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart To See Change.
        /// </summary>
        internal static string TitleRestartToSeeChange {
            get {
                return ResourceManager.GetString("TitleRestartToSeeChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Selection.
        /// </summary>
        internal static string TopSelection {
            get {
                return ResourceManager.GetString("TopSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Amount.
        /// </summary>
        internal static string TotalAmount {
            get {
                return ResourceManager.GetString("TotalAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Before Tax.
        /// </summary>
        internal static string TotalBeforeTax {
            get {
                return ResourceManager.GetString("TotalBeforeTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Price.
        /// </summary>
        internal static string TotalPrice {
            get {
                return ResourceManager.GetString("TotalPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trouble Logging In?.
        /// </summary>
        internal static string Trouble_Logging_In {
            get {
                return ResourceManager.GetString("Trouble_Logging_In", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Price.
        /// </summary>
        internal static string UnitPrice {
            get {
                return ResourceManager.GetString("UnitPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View All.
        /// </summary>
        internal static string ViewAll {
            get {
                return ResourceManager.GetString("ViewAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WEAK.
        /// </summary>
        internal static string WEAK {
            get {
                return ResourceManager.GetString("WEAK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight(Kg).
        /// </summary>
        internal static string Weight {
            get {
                return ResourceManager.GetString("Weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        internal static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Lahma.
        /// </summary>
        internal static string WelcometoLahma {
            get {
                return ResourceManager.GetString("WelcometoLahma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WithoutFat.
        /// </summary>
        internal static string Without_Fat {
            get {
                return ResourceManager.GetString("Without Fat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write what you want to tell the butcher.
        /// </summary>
        internal static string WriteTobutcher {
            get {
                return ResourceManager.GetString("WriteTobutcher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write your comment here.
        /// </summary>
        internal static string WriteYourCommentHere {
            get {
                return ResourceManager.GetString("WriteYourCommentHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong Password.
        /// </summary>
        internal static string WrongPassword {
            get {
                return ResourceManager.GetString("WrongPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YOUR RATING.
        /// </summary>
        internal static string YOURRATING {
            get {
                return ResourceManager.GetString("YOURRATING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your mail will register to us as a customer.
        /// </summary>
        internal static string YourRegisterToUs {
            get {
                return ResourceManager.GetString("YourRegisterToUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YOUR REVIEW.
        /// </summary>
        internal static string YOURREVIEW {
            get {
                return ResourceManager.GetString("YOURREVIEW", resourceCulture);
            }
        }
    }
}
